### ISSUE TITLE
[front-end] Add iOS home screen icon

### ISSUE THREAD

**Issue by otsugua** [ruisaraiva19/favycon#108]
Not sure about Android but it should be the same for now.

This is the current implementation on iOS: 
![image](https://user-images.githubusercontent.com/7356098/85199469-c9bcbb00-b2e7-11ea-96a3-36779eff934a.png)

**Comment by otsugua** [comment]
![iOS@2x](https://user-images.githubusercontent.com/9093629/82738075-1931ba80-9d2d-11ea-9df9-6db885fbe544.png)

**Comment by ruisaraiva19** [comment]
@otsugua please export this icon as SVG and then I can resize it for all iOS recommended sizes.

**Comment by otsugua** [comment]
@ruisaraiva19 here it is — https://d.pr/f/Gd7YW9
