### ISSUE TITLE
[front-end] Add E2E tests

### ISSUE THREAD

**Issue by ruisaraiva19** [ruisaraiva19/favycon#135]
- [x] setup [Cypress](https://www.cypress.io/)
- [x] add GitHub action to run e2e tests on each Vercel deploy

E2E tests list:
- [x] title copy
- [x] body/description copy
- [x] footer copy
- [x] drag & drop area copy
- [x] drag & drop footer copy
- [x] drop file error messages

**Comment by otsugua** [comment]
@ruisaraiva19 created a list of scenarios on Notion: 
https://www.notion.so/Scenarios-67545ab9acf64030b4e7d6173fca1b11

These are for the messages that show depending on the combination of specs.

**Comment by ruisaraiva19** [comment]
> @ruisaraiva19 created a list of scenarios on Notion:
> https://www.notion.so/Scenarios-67545ab9acf64030b4e7d6173fca1b11
> 
> These are for the messages that show depending on the combination of specs.

@otsugua nice 💪.
I'm going to make e2e tests for those scenarios 🧪.
