### ISSUE TITLE
[front-end] Add dark/light mode toggle

### ISSUE THREAD

**Issue by ruisaraiva19** [ruisaraiva19/favycon#14]
To-Do:
- [x] Add assets (ask @otsugua to export them)
- [x] Add dark/light mode toggle (use [this hook](https://github.com/donavon/use-dark-mode))

**Comment by rgllm** [comment]
@ruisaraiva19 @eduardoPinto12 for the default option we can use this:

```
/* Light mode */
@media (prefers-color-scheme: light) {
}

/* Dark mode */
@media (prefers-color-scheme: dark) {
}
```

**Comment by ruisaraiva19** [comment]
> @ruisaraiva19 @eduardoPinto12 for the default option we can use this:
> 
> ```
> /* Light mode */
> @media (prefers-color-scheme: light) {
> }
> 
> /* Dark mode */
> @media (prefers-color-scheme: dark) {
> }
> ```

We want something more than that 😉.

**Comment by ruisaraiva19** [comment]
@otsugua we need the assets ASAP 🙂.
