### ISSUE TITLE
[front-end] Add dropdown

### ISSUE THREAD

**Issue by ruisaraiva19** [ruisaraiva19/favycon#8]
To-Do:
- [ ] create dropdown menu component (light & dark versions)
- [x] add new Favycon SVG
- [ ] ask @otsugua about the "Get updates on new stuff" link.

**closed**
![closed](https://d.pr/i/iCG5mF+)

**opened light**
![opened-light](https://d.pr/i/b8pW8S+)

**opened dark**
![opened-dark](https://d.pr/i/O3JaMA+)

**Comment by ruisaraiva19** [comment]
@rgllm I just updated this issue description with the updated design and more details.

**Comment by rgllm** [comment]
@ruisaraiva19 two questions:

1. The closed label is passed as props. Should I add the option to pass optionally an image?

2. This https://d.pr/i/URGKJF is hardcoded, I only added a boolean option to show or hide apps.

Do you agree with this approach?

**Comment by ruisaraiva19** [comment]
@rgllm sounds good!

**Comment by ruisaraiva19** [comment]
@rgllm I just updated this issue description with the MVP design.

**Comment by ruisaraiva19** [comment]
@rgllm I just updated this issue description with the 13-04-2020 design.

**Comment by ruisaraiva19** [comment]
@rgllm What's the status on this issue? 🙂

**Comment by rgllm** [comment]
@ruisaraiva19 I hadn't the time during the week to tackle this. Now that the design is finished I will work on this.

**Comment by ruisaraiva19** [comment]
> @ruisaraiva19 I hadn't the time during the week to tackle this. Now that the design is finished I will work on this.

Nice I'm finishing the upload flow :)

**Comment by otsugua** [comment]
Isto está on hold
